"""Change answers.value to Integer

Revision ID: ce69890cf3a1
Revises: 992688f99721
Create Date: 2025-05-11 14:45:06.468770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce69890cf3a1'
down_revision: Union[str, None] = '992688f99721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'value',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="value::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'value',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
