"""add bio field to group_members

Revision ID: f22692de6fa
Revises: abcd1234567890_add_gender_fields
Create Date: 2025-01-28 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22692de6fa'
down_revision: Union[str, None] = 'abcd1234567890_add_gender_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'bio')
    # ### end Alembic commands ### 